import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/**
 * The facts the documentation states about the shipped surface, read from the source that owns
 * them.
 *
 * Every one of these had drifted. The privacy and install pages listed two required permissions
 * while the manifests declared five; a logo brief still carried the name this project had before
 * it was Aviary; a design note claimed a baseline count from a release ago. None of it was
 * checkable, because each figure was a sentence somebody typed.
 *
 *   npm run docs:facts          # rewrite the generated blocks
 *   npm run docs:facts -- --check   # fail if they are stale, which is what the suite runs
 *
 * A block is delimited so the prose around it stays hand-written. What is inside it is generated,
 * and `tests/docs-consistency.test.mjs` fails when a regenerated block would differ.
 */

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** Node strips TypeScript natively, so a tool can read the same module the app does. */
const importSourceModule = (relativePath) =>
  import(pathToFileURL(path.join(root, relativePath)).href);

export const START_MARKER = "<!-- docs-facts:start -->";
export const END_MARKER = "<!-- docs-facts:end -->";

/** Documents that carry a generated block. */
export const FACT_DOCUMENTS = ["README.md", "docs/INSTALL.md", "docs/PRIVACY.md", "design-qa.md"];

/** Every fact the blocks are built from, measured rather than remembered. */
export async function collectFacts() {
  const pkg = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
  const chrome = JSON.parse(await readFile(path.join(root, "src/extension/manifest.chrome.json"), "utf8"));
  const firefox = JSON.parse(await readFile(path.join(root, "src/extension/manifest.firefox.json"), "utf8"));

  const { CONTROL_CENTER_SECTION_MANIFEST } = await importSourceModule(
    "src/ui/control-center/section-manifest.ts"
  );
  const { SURFACE_SELECTORS } = await importSourceModule("src/platform/selectors.ts");

  const main = await readFile(path.join(root, "src/main.ts"), "utf8");
  const registeredModules = [...main.matchAll(/registry\.register\(/g)].length;

  const baselines = await countPngs(path.join(root, "tests/visual/baselines"));

  // Both manifests must agree; a permission on one browser and not the other is a fact the docs
  // cannot state in one sentence, so it is surfaced rather than silently flattened.
  const required = sameOrThrow(chrome.permissions, firefox.permissions, "permissions");
  const optional = sameOrThrow(
    chrome.optional_permissions ?? [],
    firefox.optional_permissions ?? [],
    "optional_permissions"
  );
  const optionalHosts = sameOrThrow(
    chrome.optional_host_permissions ?? [],
    firefox.optional_host_permissions ?? [],
    "optional_host_permissions"
  );
  const hosts = sameOrThrow(
    chrome.host_permissions ?? [],
    firefox.host_permissions ?? [],
    "host_permissions"
  );

  return {
    version: pkg.version,
    destinations: CONTROL_CENTER_SECTION_MANIFEST.length,
    destinationNames: CONTROL_CENTER_SECTION_MANIFEST.map((entry) => entry.title),
    selectorSurfaces: SURFACE_SELECTORS.length,
    registeredModules,
    visualBaselines: baselines,
    required,
    optional,
    optionalHosts,
    hosts
  };
}

async function countPngs(directory) {
  let total = 0;
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch {
    return 0;
  }
  for (const entry of entries) {
    const next = path.join(directory, entry.name);
    if (entry.isDirectory()) total += await countPngs(next);
    else if (entry.name.endsWith(".png")) total += 1;
  }
  return total;
}

function sameOrThrow(left, right, label) {
  const a = [...left].sort();
  const b = [...right].sort();
  if (a.join(",") !== b.join(",")) {
    throw new Error(
      `the Chrome and Firefox manifests disagree about ${label}: ${JSON.stringify(a)} vs ${JSON.stringify(b)}`
    );
  }
  return a;
}

const code = (values) => values.map((value) => `\`${value}\``).join(", ");

/** The generated block for one document. Each says the part of the surface that document is about. */
export function factBlock(document, facts) {
  const lines = [
    START_MARKER,
    "",
    "<!-- Generated by tools/docs-facts.mjs from the manifests and the panel's own metadata.",
    "     Edit those, then run `npm run docs:facts`. -->",
    ""
  ];

  if (document === "README.md") {
    lines.push(
      `Aviary ${facts.version} registers ${facts.registeredModules} feature modules, draws ` +
        `${facts.destinations} Control Center destinations, and watches ${facts.selectorSurfaces} ` +
        "selector surfaces on X."
    );
  } else if (document === "docs/INSTALL.md" || document === "docs/PRIVACY.md") {
    lines.push(
      `Required permissions: ${code(facts.required)}.`,
      "",
      `Optional permissions: ${code(facts.optional)}, plus optional host access to ` +
        `${code(facts.optionalHosts)}.`,
      "",
      `Host access: ${code(facts.hosts)}.`,
      "",
      "Both browser manifests declare exactly this set. Removing the extension the ordinary way " +
        "deletes everything it stored, including the library."
    );
  } else if (document === "design-qa.md") {
    lines.push(
      `Aviary ${facts.version}: ${facts.destinations} destinations, ` +
        `${facts.visualBaselines} committed PNG baselines, ` +
        `${facts.selectorSurfaces} selector surfaces.`
    );
  } else {
    throw new Error(`no generated block is defined for ${document}`);
  }

  lines.push("", END_MARKER);
  return lines.join("\n");
}

/** Replaces the block in a document's text. Throws when the markers are missing. */
export function replaceBlock(text, block, document) {
  const start = text.indexOf(START_MARKER);
  const end = text.indexOf(END_MARKER);
  if (start < 0 || end < 0 || end < start) {
    throw new Error(`${document} is missing the ${START_MARKER} / ${END_MARKER} pair`);
  }
  return text.slice(0, start) + block + text.slice(end + END_MARKER.length);
}

/** The documents that would change if the blocks were regenerated now. */
export async function staleFactDocuments() {
  const facts = await collectFacts();
  const stale = [];
  for (const document of FACT_DOCUMENTS) {
    const file = path.join(root, document);
    const text = await readFile(file, "utf8");
    if (replaceBlock(text, factBlock(document, facts), document) !== text) stale.push(document);
  }
  return stale;
}

async function main() {
  const check = process.argv.includes("--check");
  const facts = await collectFacts();
  const changed = [];
  for (const document of FACT_DOCUMENTS) {
    const file = path.join(root, document);
    const text = await readFile(file, "utf8");
    const next = replaceBlock(text, factBlock(document, facts), document);
    if (next === text) continue;
    changed.push(document);
    if (!check) await writeFile(file, next, "utf8");
  }

  if (check && changed.length > 0) {
    console.error(`These documents state facts the source no longer supports: ${changed.join(", ")}`);
    console.error("Run: npm run docs:facts");
    process.exit(1);
  }
  console.log(
    check
      ? "Documentation facts are current."
      : changed.length > 0
        ? `Rewrote ${changed.join(", ")}.`
        : "Documentation facts were already current."
  );
}

if (path.resolve(process.argv[1] ?? "") === path.resolve(fileURLToPath(import.meta.url))) {
  await main();
}
