import { execFileSync } from "node:child_process";

/**
 * What may travel in `dist/aviary-source-v<version>.zip`, and how to read what did.
 *
 * The archive is published beside the installable packages, so its contents are as public as the
 * repository is. `walkSource` in `tools/build.mjs` decided them by skipping a fixed list of
 * directories and image extensions, which knew nothing about `.gitignore`: v1.48.1 shipped
 * `CLAUDE.md`, the private working notes, and `tools/i18n-manifest.json`, a generated file. The
 * working notes are the worse half. They are the one file the repository's own rules let carry
 * anything, precisely because they are never published.
 *
 * Git owns the answer to "is this file part of the source", so it is asked rather than
 * re-implemented here. `EXCLUDED_SOURCE_PATHS` is the floor for a checkout with no git available,
 * which is what extracting this very archive and building from it looks like. It is named rather
 * than derived, so it is checked even when git did answer: those paths are never source, whatever
 * a stray `.gitignore` edit says.
 */
export const EXCLUDED_SOURCE_PATHS = [
  "CLAUDE.md",
  "CODEX_CHANGELOG.md",
  ".claude/",
  // Generated by `tools/i18n-extract.mjs`, not an input to the build.
  "tools/i18n-manifest.json",
  // Where `tools/yt-dlp-helper.mjs` writes media, under names taken from post titles.
  "aviary-downloads/"
];

/** True when a path is one the floor keeps out, directory prefixes included. */
export function isExcludedSourcePath(name) {
  return EXCLUDED_SOURCE_PATHS.some((entry) =>
    entry.endsWith("/") ? name === entry.slice(0, -1) || name.startsWith(entry) : name === entry
  );
}

/**
 * Which of `names` git ignores, and whether git could answer at all.
 *
 * `git check-ignore` exits 1 when nothing matches, which is the good case and not an error. Any
 * other failure means no answer was obtained, and the caller decides whether that is a warning or
 * a fallback rather than being handed an empty list that looks like a clean result.
 */
export function ignoredPaths(root, names) {
  if (names.length === 0) return { checked: true, ignored: [] };
  try {
    // `-z` on both sides of the pipe. Without it git applies `core.quotePath` and hands back
    // `"docs/notas-caf\303\251.md"` for anything non-ASCII, which matches no walked path, so the
    // file would be packed anyway and then named, in its mangled form, by the gate that refuses
    // the archive. A downloaded video titled in any non-Latin script is enough to reach that.
    const output = execFileSync("git", ["check-ignore", "-z", "--stdin"], {
      cwd: root,
      input: `${names.join("\0")}\0`,
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"]
    });
    return { checked: true, ignored: output.split("\0").filter(Boolean) };
  } catch (error) {
    // Exit 1 is "nothing matched", which is the good case and not a failure to answer.
    if (error.status === 1) return { checked: true, ignored: [] };
    return { checked: false, ignored: [] };
  }
}

/**
 * Entry names read out of a store ZIP's central directory.
 *
 * The archive is written by this repository with no compression and no ZIP64 records, so the
 * central directory is walked directly instead of adding a dependency to read six megabytes of
 * names. A malformed record throws rather than returning the entries found so far: a truncated
 * listing would report a clean archive.
 */
export function zipEntryNames(bytes) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  let end = -1;
  for (let offset = bytes.byteLength - 22; offset >= 0; offset -= 1) {
    if (view.getUint32(offset, true) === 0x06054b50) {
      end = offset;
      break;
    }
  }
  if (end < 0) throw new Error("no end-of-central-directory record");

  const count = view.getUint16(end + 10, true);
  let cursor = view.getUint32(end + 16, true);
  const decoder = new TextDecoder();
  const names = [];
  for (let index = 0; index < count; index += 1) {
    if (view.getUint32(cursor, true) !== 0x02014b50) {
      throw new Error(`central directory entry ${index} is malformed`);
    }
    const nameLength = view.getUint16(cursor + 28, true);
    const extraLength = view.getUint16(cursor + 30, true);
    const commentLength = view.getUint16(cursor + 32, true);
    names.push(decoder.decode(bytes.subarray(cursor + 46, cursor + 46 + nameLength)));
    cursor += 46 + nameLength + extraLength + commentLength;
  }
  return names;
}
